#!/bin/bash
#没有传参默认关闭WebStorm;
soName="sogoupinyin"
if [ ! -n "$1" ]
then
	echo "1"
	realName="com.intellij.idea.Main"
else
	realName=$1
fi	
pid=$(ps aux | grep ${realName} |awk '{print $2}')

echo "程序pid=${pid},即将强制关闭"

kill -9 ${pid}

echo "关闭成功"
