#! /bin/bash
pid=$(ps x| grep node| grep scripts/start |awk '{print $1}') && kill -9 ${pid} &&  echo "delete pid ${pid} success!!"
cd /Users/richie/hd/hd-management-web && ws && nohup npm start >/dev/null 2>&1 &
pidd=$(ps x| grep node| grep start |awk '{print $1}') && echo "start success and New PID is ${pidd}"
