#!/bin/bash
wsName='ws'
soName="sogoupinyin"
if [ -f $1 == "ws"]
then
	echo "1"
	realName="com.intellij.idea.Main"
elif [ -f $1 == 'ws']
then
	echo "3"
else
	echo "2"
	realName=$name
fi	
#ps aux |grep $realName
#pid=$(ps aux | grep $realName |awk '{print $2}')
#echo "程序pid=$pid,即将强制关闭"

#kill -9 $pid

#echo "关闭成功"
